application: guestbook2
version: 1
runtime: python27
api_version: 1
threadsafe: true

Libraries:
name: webapp2
version: latest
name: jinja2
version: lastest

handlers:
url: /stylesheets
static_dir: stylesheets

url: /.*
script: guestbook2.application
login: required